FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y curl docker.io

RUN curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

RUN groupadd -f docker && usermod -aG docker jenkins

USER jenkins